changed header markup and some style
sigizmunde/dervi-filmoteka pull request #2
Opened 2022-06-04 17:26 UTC by Shan-Vision

header is adaptive now.
on view width 320px display flex from logo is pulling out the navigation. thats have to be fixed.

2022-06-04 18:40 UTC, sigizmunde requested changes

2022-06-04 18:40 UTC, sigizmunde commented on src/index.html
> +    <!-- <include src="./partials/modal.html"></include> -->
1. когда спрятан этот инклюд, код выдает ошибку (элемента же нет)

можешь отключить драфты скриптов от индекс.джс, чтобы можно было верстку смотреть

2. У меня вообще ничего не отображается почему-то — только логотип

2022-06-04 21:12 UTC, Shan-Vision commented on src/index.html
> +    <!-- <include src="./partials/modal.html"></include> -->
все понятно, щас сделаю

2022-06-05 08:47 UTC, sigizmunde approved these changes

2022-06-05 08:48 UTC, merged