add Class local-storage
sigizmunde/dervi-filmoteka pull request #22
Opened 2022-06-09 19:45 UTC by Yauheni2021

2022-06-09 21:58 UTC, sigizmunde requested changes

2022-06-09 21:58 UTC, sigizmunde commented on src/js/data.js
а зачем объявление новой функции внутри?
можно просто вот так
getWatched(key) {
      try {
        const serializedData = localStorage.getItem(key);
        return serializedData === null ? [] : JSON.parse(serializedData);
      } catch (err) {
        console.error('Get state error: ', err);
      }
      return watchedArr;
  }

2022-06-09 21:58 UTC, sigizmunde commented on src/js/data.js
и здесь тоже стрелка внутри не нужна
getQueue(key) => {
      try {
        const serializedData = localStorage.getItem(key);
        return serializedData === null ? [] : JSON.parse(serializedData);
      } catch (err) {
        console.error('Get state error: ', err);
      }
    return queueArr;
  };

2022-06-09 22:11 UTC, sigizmunde commented on src/js/data.js
кроме того, key не нужен — тут просто жестко задай localStorage.getItem('watched'); (и из параметров key убирай)

а в следующей функции, соответственно, используй localStorage.getItem('queue');

2022-06-10 16:06 UTC, Yauheni2021 commented
Change Class local-storage

2022-06-10 17:29 UTC, sigizmunde approved these changes

2022-06-10 17:29 UTC, merged